### ISSUE TITLE
GitHub Flow構築の調査

### ISSUE THREAD

**Issue by MaximizedOwl** [MaximizedOwl/among-status#42]
# 調査したいこと
GitHub Flowについてと、その実現の仕方。

# 背景・経緯
開発環境を整える一環で、ステージング環境を作成したりテストの導入を行うことにした。
その中で、いままでは直接mainブランチにプッシュしていたものを、一旦プルリクとして投げて、コードレビューやテストを行ってからマージするようにする必要性を感じた。

感じた理由としては、一般公開して使ってくれている人もいるので、バグのあるようなコードを公開されるmainブランチに取り込ませるわけにはいかなくなってきたため。
あとは学習のため。

GitHub Flowにした理由としては下記2点。
1. Git Flowより簡単
2. 今回のプロジェクト的に複雑なフローを組む必要がない。

# 開始時の状況
- コードは直接mainブランチにプッシュしている。
- プルリクエストはしていない。
- 本番環境のみ。ステージング環境はない。

# タスクリスト
- [x] プッシュとプルリクの関係性の理解を詰める。
- [x] 『GitHubの教科書』を読む
- [x] ネットで他の参考資料を3つほど読む。

# 障壁
いまのところ不明

# その他
- 派生元: #13

**Comment by MaximizedOwl** [comment]
『GitHubの教科書』の例だと、GitHub Flowはブランチからのmaster、今で言うところのmainに直接プルリクを送っている。
これだとステージング環境があるときの場合にどうしているかわからない。おそらく、mainブランチのところがステージングのブランチになって、ステージング環境でのテストがOKならmainに取り込むプルリクをなげることになるんだろう。

**Comment by MaximizedOwl** [comment]
資料リストアップ。下記を読んでみる。
検索ワードは「GitHub Flow ステージング」。

1. https://www.slideshare.net/takemikami/githubgithub-flow
2. https://www.wantedly.com/companies/tutorial/post_articles/297067
3. https://techblog.exawizards.com/entry/2021/01/21/111031

**Comment by MaximizedOwl** [comment]
# Git Flow
- 複雑
- きめ細やかなので、慣れてしまえば大人数での開発に最適?

# GitHub Flow
- わかりやすい
- 導入も楽そう
- テストが各ブランチになってしまう。

# GitLab Flow
- 本番(プロダクション)環境と各ブランチの間にプレプロダクション(ステージング?)環境がある。
- 理想としているやつに近い?
- https://postd.cc/gitlab-flow/

**Comment by MaximizedOwl** [comment]
https://github.com/MaximizedOwl/among-status/issues/42#issuecomment-860344533
について

GitLab Flowの4つ目の記事がわかりやすかった。
- https://qiita.com/tlta-bkhn/items/f2950aaf00bfb6a8c30d

実務だと複数人で開発するため、個人がステージング環境(環境A)で検証する以外に、他の開発者らがステージングで検証したものをマージして検証する環境Bが必要そう。これがプレプロダクション環境になると思う。で、そこでOKなら晴れてプロダクション環境(環境C)にcherrypicするかプルリクするかしてGitHub Actionsを利用して本番環境にデプロイすることになりそう。

これを踏まえると、個人開発の場合はGitHub Flowでよさそう。
なぜなら、複数人での開発ではないために各々の開発を併せて本番リリース前検証する環境Bがいらないから。
つまり、ローカル環境(featureブランチ)、プレプロダクション環境(メイン、masterブランチ)、プロダクション環境(プロダクションブランチ)があればいいんだと思う。

**Comment by MaximizedOwl** [comment]
と思ったけど、自分がやりたいのはGitFeature Flowなのかもしれない。
https://www.wantedly.com/companies/tutorial/post_articles/297067

**Comment by MaximizedOwl** [comment]
ステージング環境とプレプロダクション環境の違い

ほぼ一緒。呼び方が違うだけのようなもの。

Wikipedia「Environments」より
https://en.wikipedia.org/wiki/Deployment_environment

**Comment by MaximizedOwl** [comment]
プレビューチャンネルとは別に、ステージング環境を用意することにした。
参考文献は下記。
https://qiita.com/hirothings/items/c6140526fbe0bbe669c1

プロジェクト「Among StatUs Staging」を作成。
https://console.firebase.google.com/u/0/project/among-status-staging/overview

プレビューチャンネルもこちらに作るようにする。

**Comment by MaximizedOwl** [comment]
現状はこう。

```bash
MyMacBookAir:among-status makiokarasawa$ git branch -a
* main
  remotes/origin/gh-pages
  remotes/origin/main
```

**Comment by MaximizedOwl** [comment]
MyMacBookAir:among-status makiokarasawa$ git branch -a
  main
* staging
  remotes/origin/gh-pages
  remotes/origin/main

**Comment by MaximizedOwl** [comment]
GitHubでstagingブランチを作成した。

**Comment by MaximizedOwl** [comment]
```bash
MyMacBookAir:among-status makiokarasawa$ git branch -d staging
error: Cannot delete branch 'staging' checked out at '/Users/makiokarasawa/Documents/Sandbox/among-status'
MyMacBookAir:among-status makiokarasawa$ git branch
  main
* staging
MyMacBookAir:among-status makiokarasawa$ git checkout main
M       firebase.json
M       package.json
M       src/paperbase/pages/game/home/main/Main.jsx
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
MyMacBookAir:among-status makiokarasawa$ git branch -d staging
Deleted branch staging (was ea0484d).
```

**Comment by MaximizedOwl** [comment]
リモートリポジトリとして設定してあるリポジトリを追加して、まずはmainだけからstagingとmainの2つにしようとおもったら怒られた。

originはユニークらしい。

```
MyMacBookAir:among-status makiokarasawa$ git remote add origin git@github.com:MaximizedOwl/among-status.git
error: remote origin already exists.
```

**Comment by MaximizedOwl** [comment]
```
MyMacBookAir:among-status makiokarasawa$ git remote -v
origin  git@github.com:MaximizedOwl/among-status.git (fetch)
origin  git@github.com:MaximizedOwl/among-status.git (push)
```

**Comment by MaximizedOwl** [comment]
いまmainの情報がremote originになっているわけだが、stagingブランチをfetchしたら上書きされるのだろうか

**Comment by MaximizedOwl** [comment]
`git checkout -b staging`をしたら自動的にpush先も`origin/staging`になっていた。

pushしたら見事stagingにだけpushされた。
また、GitHub Actionsは動作しなかった。
一番理想的ではある。
このあとは
1. GHAが動作しなかった理由
2. Firebaseのステージング環境にだけデプロイされる仕組みの実装
3. stagingをmainに取り込んだらFirebaseの本番環境にデプロイされる仕組みの構築
を予定。

**Comment by MaximizedOwl** [comment]
必要のなくなったローカルリポジトリのmainブランチの削除を行う。
このとき、間違ってもリモートのmainブランチを削除してはいけない。

**Comment by MaximizedOwl** [comment]
2. GHAが動作しなかった理由
GHAを改めて確認したところ、push時に働いていたのは2つあるうちの「firebase-hosting-merge.yml」のほう。

ここで予想できたのは下記二点。
1.  GitHub Actionsを自動化するためのymlファイルについて学ぶ必要がある。
2. Staging環境にデプロイさせるために、どこかで初期化を行う必要があるかもしれない。

あと二転三転してるがプレビューチャンネルでいい気がしてきた。
1. ローカルのstagingブランチで作成
2. ローカルのstagingブランチからリモートのstagingブランチにpush
3. 2をGitHub Actionsが検知し、リモートのmainブランチへのプルリクエスト作成とプレビューチャンネルへのデプロイが実行
4. 3がOKならマージをする
5. 4がマージされたら別のGitHub Actionsのタスクが動き、リモートのmainブランチにあるソースが本番環境へデプロイされる。

これの流れ、理解でよさそう。

**Comment by MaximizedOwl** [comment]
yamlファイルの学習をする。
下記がmainにpushされたら本番環境にデプロイするタスクを書いたyamlファイル。

```yaml
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMONG_STATUS }}'
          channelId: live 
          projectId: among-status
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

**Comment by MaximizedOwl** [comment]
変更を加える前に今の状態でプルリクエストをしてみたらどうなるのかを試してみた。

build_and_preview のタスクが走った。
https://github.com/MaximizedOwl/among-status/pull/47/checks?check_run_id=2895465524

**Comment by MaximizedOwl** [comment]
上記のプルリクエストをマージしたら、予想通りジョブが実行された。
そして無事デプロイされた。
https://github.com/MaximizedOwl/among-status/actions/runs/964565140

**Comment by MaximizedOwl** [comment]
yamlファイルの学習をする。
下記がmainにpushされたら本番環境にデプロイするタスクを書いたyamlファイル。

参考文献はこちら。
https://github.com/marketplace/actions/deploy-to-firebase-hosting
あとこれ。
https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions

```yaml
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMONG_STATUS }}'
          channelId: live 
          projectId: among-status
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```
- channelId
> If you leave this blank, a preview channel and its ID will be auto-generated per branch or PR.
とあるので、これを空白にすれば勝手にプレビューチャンネルが出来上がる。

stagingブランチにpushしたときに実行されるワークフローを作成したが、だめだった。
エラーは大きく2点。

1. 使っていないプルリクエスト用のワークフローファイルでエラー
2. 新たに作成した`firebase-hosting-merge-staging.yml`でエラー

2のエラー内容は下記。
```bash
Error: channelID is currently required
  
  The process '/usr/local/bin/npx' failed with exit code 1
  Error: The process '/usr/local/bin/npx' failed with exit code 1
  ***
    conclusion: 'failure',
    output: ***
      title: 'Deploy preview failed',
      summary: "Error: The process '/usr/local/bin/npx' failed with exit code 1"
    ***
  ***
```
